from pptx import Presentation
from pptx.util import Inches, Pt, Cm
from pptx.dml.color import RGBColor
from pptx.oxml.ns import qn
import sys
import os

def create_ppt_from_md(md_content, output_path):
    """
    根据 Markdown 内容生成 PPT。
    Markdown 规则：
    # 标题 -> 封面页 (标题 + 副标题)
    ## 标题 -> 内容页标题
    - 列表 -> 内容页正文 (支持多级列表)
    """
    try:
        prs = Presentation()
        
        # 定义幻灯片布局索引
        LAYOUT_TITLE = 0
        LAYOUT_TITLE_CONTENT = 1
        
        lines = md_content.split('\n')
        current_slide = None
        current_body = None
        
        # 默认中文字体
        DEFAULT_FONT = '微软雅黑'
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
                
            if line.startswith('# '):
                # 封面页
                slide = prs.slides.add_slide(prs.slide_layouts[LAYOUT_TITLE])
                title = slide.shapes.title
                subtitle = slide.placeholders[1]
                
                parts = line[2:].split(' - ')
                title.text = parts[0]
                if len(parts) > 1:
                    subtitle.text = parts[1]
                else:
                    subtitle.text = "Generated by SeerLord AI"
                    
                # 设置字体
                for shape in [title, subtitle]:
                    if not shape or not shape.text_frame: continue
                    for paragraph in shape.text_frame.paragraphs:
                        paragraph.font.name = DEFAULT_FONT
                        # 尝试设置东亚字体
                        try:
                            paragraph.font.element.rPr.rFonts.set(qn('w:eastAsia'), DEFAULT_FONT)
                        except:
                            pass

            elif line.startswith('## '):
                # 内容页
                slide = prs.slides.add_slide(prs.slide_layouts[LAYOUT_TITLE_CONTENT])
                current_slide = slide
                title = slide.shapes.title
                title.text = line[3:]
                
                # 获取内容占位符
                current_body = slide.placeholders[1].text_frame
                current_body.clear() # 清空默认内容
                
                # 设置标题字体
                for paragraph in title.text_frame.paragraphs:
                    paragraph.font.name = DEFAULT_FONT

            elif line.startswith('- ') or line.startswith('* '):
                # 列表内容
                if current_body:
                    p = current_body.add_paragraph()
                    text = line[2:]
                    level = 0
                    
                    # 简单处理缩进
                    # 实际 Markdown 可能用空格缩进，这里假设 line.strip() 去掉了前导空格
                    # 如果要支持多级列表，需要分析原始行的前导空格
                    # 这里简化处理：如果在 Markdown 中使用了缩进，通常不会被 strip 掉前面的空格吗？
                    # 修正：line = line.strip() 会去掉所有前导空格。
                    # 为了支持层级，我们需要重新遍历，不使用 strip
                    pass 
                    p.text = text
                    p.level = level
                    p.font.name = DEFAULT_FONT

            else:
                # 普通文本，作为第一级列表或者追加到上一个段落
                if current_body:
                    p = current_body.add_paragraph()
                    p.text = line
                    p.font.name = DEFAULT_FONT

        prs.save(output_path)
        return True, f"Successfully created PPT at {output_path}"
        
    except Exception as e:
        sys.stderr.write(f"Error creating PPT: {e}\n")
        return False, str(e)

def create_ppt_from_md_file(md_path, output_path):
    if not os.path.exists(md_path):
        return False, f"Markdown file not found: {md_path}"
    
    try:
        with open(md_path, 'r', encoding='utf-8') as f:
            content = f.read()
        return create_ppt_from_md(content, output_path)
    except Exception as e:
        sys.stderr.write(f"Error reading MD file: {e}\n")
        return False, str(e)
