import os
import sys
from pathlib import Path
from sqlalchemy.schema import CreateTable

# Add project root to sys.path
root_path = Path(__file__).resolve().parents[1]
sys.path.append(str(root_path))

from server.core.database import Base, engine
# Import all models to ensure they are registered in Base.metadata
# We import server.db.models which should import all sub-models
import server.db.models

def export_schema():
    """
    Export the database schema to SQL statements.
    """
    output_file = root_path / "db_schema.sql"
    
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("-- SeerLord AI Database Schema\n")
        f.write("-- Generated by scripts/export_schema.py\n")
        f.write("-- Database Dialect: PostgreSQL\n\n")
        
        # Sort tables by dependency (foreign keys)
        sorted_tables = Base.metadata.sorted_tables
        
        for table in sorted_tables:
            create_table_stmt = CreateTable(table)
            # Compile the statement using the PostgreSQL dialect
            # removing the schema binding to avoid 'schema "public" does not exist' if not handled
            compiled = create_table_stmt.compile(engine)
            f.write(str(compiled).strip() + ";\n\n")

if __name__ == "__main__":
    print("Exporting database schema...")
    try:
        export_schema()
        print(f"Schema successfully exported to {root_path / 'db_schema.sql'}")
    except Exception as e:
        print(f"Error exporting schema: {e}")
        import traceback
        traceback.print_exc()
